sonar.projectKey=ArchLens-Fiap_archlens-infra-db
sonar.organization=archlens-fiap
sonar.projectName=archlens-infra-db
sonar.sources=.
sonar.exclusions=.github/**
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
